### ISSUE TITLE
[epic] Upgrade to CKAN v2.9 (activity)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckanext-versions#6]
* [ ] Prep work to build on ckanext-versions (2d?)
  * [x] Branch current main to v2.8f
  * [ ] Convert README to markdown (0.25d)
  * [x] Setup automated testing using github actions (0.5d)
  * [x] Get up-to date with new activity feature of CKAN 2.9 (1d)
* [ ] Refactor model to new setup (as per table design below in analysis) (0.5d)
  * [x] Add resource_id
    * [ ] Make it nullable
  * [x] Connect with activity table (0.5d)
* [ ] Check "it can run" on v2.9
  * [ ] Check tests

**Comment by rufuspollock** [comment]
@tomeksabala i was wondering how it was going doing the pure upgrade to v2.9 with the activity item and keeping the standard dataset level revisioning (i know that @pdelboca is working on adding resource versioning in #7)

I'm wondering if we will want to have 2 branches here one for dataset level versioning and one for resource level versioning.

/cc @shevron @anuveyatsu
